data:
  name: [None, "vKitti2"]
  # split: [None, "eval_visualize_from_bts"]     # for qualitative/quantitative output in the paper
  split: [None, "test"]     # for quantitative output
  tr_crop_size: [352, 704]
  te_crop_size: [352, 704]
  norm_type: "imagenet-norm"